<?php
/**
 * CMMS Webhook API
 *
 * One webhook endpoint per form. External systems POST JSON to:
 *   /wp-json/cmms-light/v1/webhook/<form_slug>
 * with Header: Authorization: Bearer <api_key>
 *
 * Each form has at most one active API key. We store SHA-256 of the key,
 * never the key itself — once issued, it cannot be retrieved, only rotated.
 *
 * Design rationale (1.14.94):
 *   - The webhook reuses CMMS_Forms::process_submission so the mapping
 *     from "incoming data" to "new task" stays in ONE place. Public-form
 *     submissions and webhook submissions follow the same code path.
 *   - Webhook callers may omit any field (per spec). Required-field
 *     validation is bypassed via $skip_required=true. Standard task
 *     fields (title/description/priority/status) arrive at top level
 *     of the JSON body; custom dynamic fields use the form's label
 *     names (we resolve label -> field_id) OR field_<id> directly.
 *   - Unknown JSON keys are silently ignored (per spec).
 *   - File uploads are supported via multipart/form-data (preferred)
 *     and via URL references inside the JSON body (downloaded server-
 *     side then attached to the resulting task).
 */
if ( ! defined( 'ABSPATH' ) ) exit;

class CMMS_Webhook {

    const ROUTE_NAMESPACE = 'cmms-light/v1';

    /**
     * Hook into WordPress REST API. Called from CMMS_Plugin::run via
     * the 'rest_api_init' action.
     */
    public static function register_routes() {
        // Slug regex deliberately accepts a wide character set. Slugs are
        // generated by sanitize_title() which on Hebrew/Arabic/Cyrillic
        // installs preserves Unicode word characters as percent-encoded
        // sequences in URLs. Restricting to [a-z0-9-] would break those
        // installs entirely. We rely on form-existence check (get_by_slug)
        // to reject malformed/non-existent values — the regex only needs
        // to be permissive enough to let the request reach our handler.
        register_rest_route( self::ROUTE_NAMESPACE, '/webhook/(?P<slug>[^/]+)', array(
            'methods'             => 'POST',
            'callback'            => array( __CLASS__, 'handle_request' ),
            // We do our own auth (Bearer token in header). REST permission
            // callback must return true so WordPress doesn't reject the
            // request before we get a chance to read the Authorization header.
            'permission_callback' => '__return_true',
            'args'                => array(
                'slug' => array(
                    'required'          => true,
                    'sanitize_callback' => 'sanitize_title',
                ),
            ),
        ) );
    }

    // ─────────────────────────────────────────────────────────────────
    // API KEY MANAGEMENT
    // ─────────────────────────────────────────────────────────────────

    /**
     * Generate a new API key for a form. Returns the FULL plaintext key
     * exactly once — the caller is responsible for showing it to the
     * user. We only store the SHA-256 hash.
     *
     * If a key already exists for this form, it is replaced (rotated).
     *
     * @return string|WP_Error Plaintext key on success.
     */
    public static function generate_key( $form_id, $account_id ) {
        global $wpdb;
        $form_id    = (int) $form_id;
        $account_id = (int) $account_id;

        // Confirm the form belongs to the account (defense in depth).
        $form = CMMS_Forms::get( $form_id );
        if ( ! $form || (int) $form->account_id !== $account_id ) {
            return new WP_Error( 'invalid_form', __( 'Form not found', 'cmms-light' ) );
        }

        // 32 bytes of randomness rendered as 64 hex chars, prefixed for
        // easy recognition. The 'cmms_' prefix lets users (and us in
        // logs) immediately see what kind of token this is.
        $random = bin2hex( random_bytes( 32 ) );
        $plain  = 'cmms_' . $random;
        $hash   = hash( 'sha256', $plain );
        // First 13 chars of the plaintext key ('cmms_' + 8 hex). Used
        // for UI display ("cmms_a3f9b2c1...") so the owner can identify
        // the key without us storing the secret.
        $prefix = substr( $plain, 0, 13 );

        $table = CMMS_DB::table( 'webhook_keys' );
        $existing = $wpdb->get_var( $wpdb->prepare(
            "SELECT id FROM $table WHERE form_id = %d",
            $form_id
        ) );

        if ( $existing ) {
            // Rotate: overwrite the existing row. We deliberately reset
            // request_count and last_used_at so the new key starts fresh.
            $wpdb->update( $table, array(
                'api_key_hash'  => $hash,
                'key_prefix'    => $prefix,
                'enabled'       => 1,
                'last_used_at'  => null,
                'request_count' => 0,
                'created_at'    => current_time( 'mysql' ),
            ), array( 'id' => (int) $existing ),
               array( '%s', '%s', '%d', '%s', '%d', '%s' ),
               array( '%d' ) );
        } else {
            $wpdb->insert( $table, array(
                'form_id'       => $form_id,
                'account_id'    => $account_id,
                'api_key_hash'  => $hash,
                'key_prefix'    => $prefix,
                'enabled'       => 1,
                'request_count' => 0,
                'created_at'    => current_time( 'mysql' ),
            ), array( '%d', '%d', '%s', '%s', '%d', '%d', '%s' ) );
        }

        return $plain;
    }

    /**
     * Revoke (delete) the API key for a form. Idempotent.
     */
    public static function revoke_key( $form_id, $account_id ) {
        global $wpdb;
        $table = CMMS_DB::table( 'webhook_keys' );
        $wpdb->delete( $table,
            array( 'form_id' => (int) $form_id, 'account_id' => (int) $account_id ),
            array( '%d', '%d' )
        );
    }

    /**
     * Get the webhook key record for a form (without the secret).
     * Returns object with id, key_prefix, enabled, last_used_at,
     * request_count, created_at — or null if no key issued.
     */
    public static function get_key_info( $form_id ) {
        global $wpdb;
        $table = CMMS_DB::table( 'webhook_keys' );
        return $wpdb->get_row( $wpdb->prepare(
            "SELECT id, form_id, account_id, key_prefix, enabled,
                    last_used_at, request_count, created_at
             FROM $table
             WHERE form_id = %d",
            (int) $form_id
        ) );
    }

    // ─────────────────────────────────────────────────────────────────
    // REQUEST HANDLING
    // ─────────────────────────────────────────────────────────────────

    /**
     * Main REST callback. Validates auth, transforms the JSON payload
     * into the post_data shape that CMMS_Forms::process_submission
     * expects, and delegates.
     */
    public static function handle_request( WP_REST_Request $request ) {
        $slug = $request->get_param( 'slug' );

        // 1. Resolve form. We need it both to find the right API key
        //    record AND to map incoming field labels to field_<id>.
        $form = CMMS_Forms::get_by_slug( $slug );
        if ( ! $form ) {
            return self::error_response( 'form_not_found', __( 'Form not found', 'cmms-light' ), 404 );
        }
        if ( ! $form->enabled ) {
            return self::error_response( 'form_disabled', __( 'Form is disabled', 'cmms-light' ), 403 );
        }

        // 2. Authenticate. The Authorization header should be:
        //    Authorization: Bearer cmms_<hex>
        $auth_header = $request->get_header( 'authorization' );
        $provided_key = self::extract_bearer_token( $auth_header );
        if ( ! $provided_key ) {
            return self::error_response( 'missing_auth', __( 'Missing Authorization header. Expected: Bearer <api_key>', 'cmms-light' ), 401 );
        }

        $key_row = self::lookup_key_by_plaintext( $provided_key );
        if ( ! $key_row ) {
            return self::error_response( 'invalid_key', __( 'Invalid API key', 'cmms-light' ), 401 );
        }
        if ( (int) $key_row->form_id !== (int) $form->id ) {
            // The key exists but belongs to a different form — same response
            // as "invalid" so we don't leak which-key-belongs-where info.
            return self::error_response( 'invalid_key', __( 'Invalid API key', 'cmms-light' ), 401 );
        }
        if ( ! $key_row->enabled ) {
            return self::error_response( 'key_disabled', __( 'API key is disabled', 'cmms-light' ), 403 );
        }

        // 3. Parse payload. JSON body OR multipart form-data (for file
        //    uploads). We accept either Content-Type.
        $content_type = (string) $request->get_header( 'content_type' );
        $is_multipart = ( stripos( $content_type, 'multipart/form-data' ) !== false );

        if ( $is_multipart ) {
            // Multipart: fields arrive in $_POST, files in $_FILES.
            $payload = $_POST;
            $files   = $_FILES;
        } else {
            // JSON body. get_json_params handles content-type 'application/json'
            // and falls back to parsing the raw body.
            $payload = $request->get_json_params();
            if ( ! is_array( $payload ) ) {
                $payload = array();
            }
            $files = array();
        }

        // 4. Test mode — return what would happen, without creating anything.
        //    Triggered by ?test=1 or "_test": true in the JSON body.
        $is_test = ( $request->get_param( 'test' ) === '1' )
                || ( ! empty( $payload['_test'] ) );

        // 5. Transform payload into the field_<id> shape that
        //    process_submission expects. Standard fields (title/description/
        //    priority/status) come through as __webhook_* keys which the
        //    forms processor understands as overrides.
        $transformed = self::transform_payload( $form, $payload, $files );

        if ( $is_test ) {
            // Compose a preview without creating anything in the DB.
            return self::success_response( array(
                'test_mode' => true,
                'would_create_task' => array(
                    'title'       => $transformed['post_data']['__webhook_title']
                                     ?? __( 'New task', 'cmms-light' ),
                    'description' => $transformed['post_data']['__webhook_description'] ?? '',
                    'priority'    => $transformed['post_data']['__webhook_priority']
                                     ?? $form->default_priority,
                    'status'      => $transformed['post_data']['__webhook_status']
                                     ?? $form->default_status,
                    'form_id'     => (int) $form->id,
                    'form_name'   => $form->name,
                    'mapped_fields' => $transformed['mapped_fields'],
                    'ignored_keys'  => $transformed['ignored_keys'],
                    'file_count'    => count( $transformed['files'] ),
                ),
            ) );
        }

        // 6. Handle file URL downloads (JSON-only). If the payload contains
        //    URL strings for file-type form fields, fetch them server-side
        //    so process_submission can attach them.
        if ( ! $is_multipart && ! empty( $transformed['file_urls'] ) ) {
            $downloaded = self::download_file_urls( $transformed['file_urls'] );
            $transformed['files'] = array_merge( $transformed['files'], $downloaded );
        }

        // 7. Delegate to the shared submission processor. skip_required=true
        //    because per spec, webhook callers may omit any field.
        $task_id = CMMS_Forms::process_submission(
            $form->slug,
            $transformed['post_data'],
            $transformed['files'],
            true,        // skip_required
            'webhook'    // source_type
        );

        // 8. Update key usage stats regardless of outcome — this helps
        //    operators debug "the integration isn't working" issues.
        self::record_key_usage( (int) $key_row->id );

        if ( is_wp_error( $task_id ) ) {
            return self::error_response(
                $task_id->get_error_code() ?: 'submission_failed',
                $task_id->get_error_message(),
                400
            );
        }

        return self::success_response( array(
            'task_id'      => (int) $task_id,
            'form_id'      => (int) $form->id,
            'ignored_keys' => $transformed['ignored_keys'],
        ) );
    }

    /**
     * Transform an incoming JSON/multipart payload into the shape
     * CMMS_Forms::process_submission expects.
     *
     * Standard top-level keys (title, description, priority, status)
     * become __webhook_* override keys.
     *
     * Dynamic field references can be either:
     *   - "field_42": value      (direct field_id reference)
     *   - "my_label": value      (label-based; matched case-insensitively
     *                             against the form's field labels)
     *
     * Returns an array with:
     *   post_data    => array keyed by field_<id> and __webhook_* keys
     *   files        => array of $_FILES-shape entries keyed by field_<id>
     *   file_urls    => array of url=>field_id for URL-based file refs
     *   mapped_fields => debug: which input key mapped to which field
     *   ignored_keys  => debug: input keys that didn't match anything
     */
    private static function transform_payload( $form, array $payload, array $files ) {
        $post_data    = array();
        $out_files    = array();
        $file_urls    = array();
        $mapped       = array();
        $ignored      = array();

        // Build a label->field map (lowercased for case-insensitive lookup).
        $form_fields = CMMS_Forms::get_fields( $form->id );
        $label_map   = array();
        $field_by_id = array();
        foreach ( $form_fields as $f ) {
            $label_map[ strtolower( trim( $f->label ) ) ] = $f;
            $field_by_id[ (int) $f->id ] = $f;
        }

        // Standard task fields. These are stored under reserved
        // __webhook_* keys so process_submission knows to use them
        // as overrides for the task's top-level columns.
        $standard_map = array(
            'title'       => '__webhook_title',
            'description' => '__webhook_description',
            'priority'    => '__webhook_priority',
            'status'      => '__webhook_status',
            // 1.15.11: allow webhook senders to set the technician
            // (assignee) and the responsible person (manager) per
            // request. Accepts a CMMS user id. Falls back to the
            // form's defaults when omitted.
            'assignee_id' => '__webhook_assignee_id',
            'manager_id'  => '__webhook_manager_id',
        );

        foreach ( $payload as $key => $value ) {
            // Reserved control keys we deliberately ignore.
            if ( $key === '_test' ) continue;

            // Standard task field.
            if ( isset( $standard_map[ $key ] ) ) {
                if ( is_scalar( $value ) ) {
                    $post_data[ $standard_map[ $key ] ] = (string) $value;
                    $mapped[ $key ] = $standard_map[ $key ];
                }
                continue;
            }

            // Direct field_<id> reference.
            if ( preg_match( '/^field_(\d+)$/', $key, $m ) ) {
                $fid = (int) $m[1];
                if ( ! isset( $field_by_id[ $fid ] ) ) {
                    $ignored[] = $key;
                    continue;
                }
                self::assign_field_value( $field_by_id[ $fid ], $value, $post_data, $file_urls );
                $mapped[ $key ] = 'field_' . $fid;
                continue;
            }

            // Label-based reference (case-insensitive).
            $lookup_key = strtolower( trim( (string) $key ) );
            if ( isset( $label_map[ $lookup_key ] ) ) {
                $field = $label_map[ $lookup_key ];
                self::assign_field_value( $field, $value, $post_data, $file_urls );
                $mapped[ $key ] = 'field_' . (int) $field->id;
                continue;
            }

            // No match — silently ignore (per spec) but record for debug.
            $ignored[] = $key;
        }

        // Multipart files: $_FILES is keyed however the client sent it
        // (e.g. "field_42" or "my_label"). Normalize to field_<id>.
        if ( ! empty( $files ) ) {
            foreach ( $files as $key => $file_info ) {
                // Direct field_<id> reference.
                if ( preg_match( '/^field_(\d+)$/', $key, $m ) && isset( $field_by_id[ (int) $m[1] ] ) ) {
                    $out_files[ $key ] = $file_info;
                    continue;
                }
                // Label-based reference.
                $lookup_key = strtolower( trim( (string) $key ) );
                if ( isset( $label_map[ $lookup_key ] ) ) {
                    $field = $label_map[ $lookup_key ];
                    if ( $field->field_type === 'file' ) {
                        $out_files[ 'field_' . (int) $field->id ] = $file_info;
                    }
                }
            }
        }

        return array(
            'post_data'     => $post_data,
            'files'         => $out_files,
            'file_urls'     => $file_urls,
            'mapped_fields' => $mapped,
            'ignored_keys'  => $ignored,
        );
    }

    /**
     * Place a single value into post_data, respecting the field's type.
     * For 'file' fields, URL strings are collected into $file_urls for
     * later server-side download.
     */
    private static function assign_field_value( $field, $value, array &$post_data, array &$file_urls ) {
        $field_id  = (int) $field->id;
        $field_key = 'field_' . $field_id;

        if ( $field->field_type === 'file' ) {
            // Accept either a string URL or an array of URLs.
            if ( is_string( $value ) && filter_var( $value, FILTER_VALIDATE_URL ) ) {
                $file_urls[ $field_key ] = array( $value );
            } elseif ( is_array( $value ) ) {
                $urls = array();
                foreach ( $value as $v ) {
                    if ( is_string( $v ) && filter_var( $v, FILTER_VALIDATE_URL ) ) {
                        $urls[] = $v;
                    }
                }
                if ( ! empty( $urls ) ) $file_urls[ $field_key ] = $urls;
            }
            return;
        }

        if ( $field->field_type === 'checkbox' ) {
            // The field options determine single vs multi semantics.
            $field_options = array_filter( array_map( 'trim', explode( ',', (string) $field->options ) ) );
            if ( ! empty( $field_options ) ) {
                // Multi-checkbox: accept array or comma-separated string.
                if ( is_string( $value ) ) {
                    $value = array_map( 'trim', explode( ',', $value ) );
                }
                if ( ! is_array( $value ) ) $value = array();
                $post_data[ $field_key ] = $value;
            } else {
                // Single yes/no: presence-as-truth, like an HTML checkbox.
                // Truthy values become "checked".
                $truthy = ( $value === true )
                       || ( $value === 1 )
                       || ( $value === '1' )
                       || ( is_string( $value ) && in_array( strtolower( $value ), array( 'true', 'yes', 'on' ), true ) );
                if ( $truthy ) {
                    $post_data[ $field_key ] = '1';
                }
            }
            return;
        }

        // Scalar fields (text, textarea, date, dropdown).
        if ( is_scalar( $value ) ) {
            $post_data[ $field_key ] = (string) $value;
        }
    }

    // ─────────────────────────────────────────────────────────────────
    // FILE URL DOWNLOAD
    // ─────────────────────────────────────────────────────────────────

    /**
     * Download URLs into temp files and return $_FILES-shaped entries.
     * One field can have multiple URLs (rare but supported). We only
     * accept reasonable MIME types and bound size to 25MB per file.
     *
     * If a download fails, we skip it silently — per the "be liberal in
     * what you accept" principle, a broken image URL shouldn't lose the
     * whole ticket.
     */
    private static function download_file_urls( array $file_urls ) {
        $out = array();
        if ( ! function_exists( 'download_url' ) ) {
            require_once ABSPATH . 'wp-admin/includes/file.php';
        }

        foreach ( $file_urls as $field_key => $urls ) {
            // process_submission only takes ONE file per field key, so we
            // only download the first URL per field. (Multiple files per
            // field would need handle_upload calls in a loop; defer to
            // a future iteration.)
            $url = is_array( $urls ) ? reset( $urls ) : $urls;
            if ( ! filter_var( $url, FILTER_VALIDATE_URL ) ) continue;

            // 25 second timeout — generous but bounded.
            $tmp = download_url( $url, 25 );
            if ( is_wp_error( $tmp ) ) continue;

            $size = @filesize( $tmp );
            if ( $size === false || $size > 25 * 1024 * 1024 ) {
                @unlink( $tmp );
                continue;
            }

            // Derive a filename from the URL path. download_url returns a
            // .tmp path; we need a sensible "name" for handle_upload.
            $parsed = wp_parse_url( $url );
            $name   = $parsed && isset( $parsed['path'] ) ? basename( $parsed['path'] ) : 'webhook-file';
            if ( $name === '' ) $name = 'webhook-file';

            // wp_check_filetype recognises by extension. For unknown
            // extensions, handle_upload's mime check will catch it.
            $type_info = wp_check_filetype( $name );
            $mime      = $type_info['type'] ?: 'application/octet-stream';

            $out[ $field_key ] = array(
                'name'     => $name,
                'type'     => $mime,
                'tmp_name' => $tmp,
                'error'    => 0,
                'size'     => $size,
            );
        }

        return $out;
    }

    // ─────────────────────────────────────────────────────────────────
    // KEY LOOKUP & USAGE
    // ─────────────────────────────────────────────────────────────────

    /**
     * Look up a key row by plaintext key. Returns the row or null.
     * Constant-time comparison via hash_equals is not applicable here —
     * we use SHA-256 lookup directly, so timing reveals only "key
     * exists or not" which is acceptable (and inherent to any lookup
     * by hash).
     */
    private static function lookup_key_by_plaintext( $plain ) {
        global $wpdb;
        $table = CMMS_DB::table( 'webhook_keys' );
        $hash  = hash( 'sha256', $plain );
        return $wpdb->get_row( $wpdb->prepare(
            "SELECT id, form_id, account_id, enabled, key_prefix
             FROM $table WHERE api_key_hash = %s",
            $hash
        ) );
    }

    /**
     * Bump request_count and last_used_at for a key. Best-effort —
     * doesn't fail the request on errors.
     */
    private static function record_key_usage( $key_id ) {
        global $wpdb;
        $table = CMMS_DB::table( 'webhook_keys' );
        $wpdb->query( $wpdb->prepare(
            "UPDATE $table
             SET request_count = request_count + 1,
                 last_used_at  = %s
             WHERE id = %d",
            current_time( 'mysql' ),
            (int) $key_id
        ) );
    }

    /**
     * Extract the bearer token from "Authorization: Bearer <token>".
     * Returns null if header is missing or malformed.
     */
    private static function extract_bearer_token( $header ) {
        if ( empty( $header ) ) return null;
        if ( preg_match( '/^Bearer\s+(\S+)$/i', trim( $header ), $m ) ) {
            return $m[1];
        }
        return null;
    }

    // ─────────────────────────────────────────────────────────────────
    // RESPONSE HELPERS
    // ─────────────────────────────────────────────────────────────────

    private static function success_response( $data ) {
        return new WP_REST_Response( array_merge( array( 'success' => true ), $data ), 200 );
    }

    private static function error_response( $code, $message, $http_status ) {
        return new WP_REST_Response( array(
            'success' => false,
            'code'    => $code,
            'message' => $message,
        ), (int) $http_status );
    }

    // ─────────────────────────────────────────────────────────────────
    // DOCUMENTATION HELPERS (used by the form-edit UI)
    // ─────────────────────────────────────────────────────────────────

    /**
     * Build a schema description of accepted JSON keys for a form.
     * Used by the form-edit UI to render the documentation panel.
     */
    public static function get_schema_for_ui( $form ) {
        $fields = CMMS_Forms::get_fields( $form->id );

        $standard = array(
            array( 'key' => 'title',       'type' => 'string', 'note' => __( 'Task title. Default: "New task" if omitted.', 'cmms-light' ) ),
            array( 'key' => 'description', 'type' => 'string', 'note' => __( 'Task description.', 'cmms-light' ) ),
            array( 'key' => 'priority',    'type' => 'string', 'note' => __( "One of: low, normal, high, urgent. Default: form's default.", 'cmms-light' ) ),
            array( 'key' => 'status',      'type' => 'string', 'note' => __( "One of: open, in_progress, completed. Default: form's default.", 'cmms-light' ) ),
            array( 'key' => 'manager_id',  'type' => 'integer', 'note' => __( "CMMS user id of the responsible person (אחראי). Default: form's default.", 'cmms-light' ) ),
            array( 'key' => 'assignee_id', 'type' => 'integer', 'note' => __( "CMMS user id of the technician (מוקצה ל). Default: form's default.", 'cmms-light' ) ),
        );

        $dynamic = array();
        foreach ( $fields as $f ) {
            $entry = array(
                'key'   => 'field_' . (int) $f->id,
                'label' => $f->label,
                'type'  => self::ui_type_for( $f->field_type ),
            );
            $opts = array_filter( array_map( 'trim', explode( ',', (string) $f->options ) ) );
            if ( ! empty( $opts ) ) {
                $entry['accepted_values'] = $opts;
            }
            $dynamic[] = $entry;
        }

        return array( 'standard' => $standard, 'dynamic' => $dynamic );
    }

    private static function ui_type_for( $field_type ) {
        $map = array(
            'text'     => 'string',
            'textarea' => 'string',
            'date'     => 'string (YYYY-MM-DD)',
            'dropdown' => 'string',
            'checkbox' => 'boolean or array',
            'file'     => 'string (URL) or multipart upload',
        );
        return $map[ $field_type ] ?? 'string';
    }

    /**
     * Build the public webhook URL for a form. Returns absolute URL.
     */
    public static function webhook_url( $form ) {
        return rest_url( self::ROUTE_NAMESPACE . '/webhook/' . $form->slug );
    }
}
